### ISSUE TITLE
Code along

### ISSUE THREAD

**Issue by pdavie** [rieckpil/testing-spring-boot-applications-masterclass#19]
I am really enjoying the course, but I am wondering if I am missing something.  It would be good to have a branch which has the bones of the application only and allows the participant to *code along* and therefore learn by doing.  With the test classes already complete in the git repository, it discourages this approach. 

I am thinking that a separate branch could include the final test code, such that anyone wanting all of the tests for reference can grab it, but the default is for none of the test classes to be provided encouraging participation (rather than just passive watching of each video).

Any thoughts?

**Comment by rieckpil** [comment]
There's now a `code-along` branch with the (almost) empty test shells for an improved coding along experience 🚀
